POST http://localhost:3000/api/home/create
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDE4QGFzZC5jb20iLCJ1c2VySWQiOiI2NDQ0ZjlmZjZjODE4YmQ1MDkxMDY4MzkiLCJpYXQiOjE2ODM0NTYxNjUsImV4cCI6MTY4MzQ1OTc2NX0.rzZ55wKARrZFnKj08eA3CN1Kf8tkTaP7m1kDFDg8-DY
Content-Type: application/json; charset=utf-8

{
  "name": "casa18",
  "type": "Roof"
}

###

POST http://localhost:3000/api/home/create
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDE3QGFzZC5jb20iLCJ1c2VySWQiOiI2NDQ0ZTFiYmU2ZWFjMzEzNjgyNmQ4ZTMiLCJpYXQiOjE2ODM0NTYxMjgsImV4cCI6MTY4MzQ1OTcyOH0.Lke8LCypAwJ7atnlNa8txltnkBTLTWmtWV66UqrpQq8
Content-Type: application/json; charset=utf-8

{
  "name": "akesta",
  "type": "Roof"
}