POST http://localhost:3000/api/device/create/64590d50817d2f71ff043147
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDEyQGFzZC5jb20iLCJ1c2VySWQiOiI2NDQ0ZDlkMWU2ZWFjMzEzNjgyNmQ4YjAiLCJpYXQiOjE2ODM1NzA2OTIsImV4cCI6MTY4MzU3NDI5Mn0.g2WxG16JWeodSKeS7544qS8Bzl-lQaBs6_tdEwpHbk8
Content-Type: application/json; charset=utf-8

{
  "name": "casa12f",
  "type": "Roof"
}

###

POST http://localhost:3000/api/device/create/64590d50817d2f71ff043147
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDIwQGFzZC5jb20iLCJ1c2VySWQiOiI2NDQ5NDdmN2MyYjJjNTU0N2NjZjM5NGIiLCJpYXQiOjE2ODM3Mjg3MzgsImV4cCI6MTY4MzczMjMzOH0.B9O-PohsdZt75pqAydRtxjb5uTdkFn1sCs5nt4iQy2U
Content-Type: application/json; charset=utf-8

{
  "name": "casa20b",
  "type": "Roof"
}

###

POST http://localhost:3000/api/device/create/645ba99be178f0bb8f4d1097
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDIwQGFzZC5jb20iLCJ1c2VySWQiOiI2NDQ5NDdmN2MyYjJjNTU0N2NjZjM5NGIiLCJpYXQiOjE2ODM3Mjg3MzgsImV4cCI6MTY4MzczMjMzOH0.B9O-PohsdZt75pqAydRtxjb5uTdkFn1sCs5nt4iQy2U
Content-Type: application/json; charset=utf-8

{
  "name": "dev2",
  "virtual": true,
  "typeString": "Plug"
}