GET http://localhost:3000/api/device/all
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDlAYXNkLmNvbSIsInVzZXJJZCI6IjY0NDRkOGYyZTZlYWMzMTM2ODI2ZDg5ZiIsImlhdCI6MTY4NDA3MjU1NywiZXhwIjoxNjg0MDc2MTU3fQ.14o2uhpbqwqH0GPcfsKq5R45M0oSktfMUV3HdBy-BFM

###

GET http://localhost:3000/api/device/home/645fb2ab01bcfdada2c68abf
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDlAYXNkLmNvbSIsInVzZXJJZCI6IjY0NDRkOGYyZTZlYWMzMTM2ODI2ZDg5ZiIsImlhdCI6MTY4NDA4MzY5OSwiZXhwIjoxNjg0MDg3Mjk5fQ.rYV3USpbpLlmuwI_7MWpnxtceYTGDCD4FREpK6O-ioM

###

GET http://localhost:3000/api/home/645fb2ab01bcfdada2c68abf
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDlAYXNkLmNvbSIsInVzZXJJZCI6IjY0NDRkOGYyZTZlYWMzMTM2ODI2ZDg5ZiIsImlhdCI6MTY4NDA4MzY5OSwiZXhwIjoxNjg0MDg3Mjk5fQ.rYV3USpbpLlmuwI_7MWpnxtceYTGDCD4FREpK6O-ioM

###

GET http://localhost:3000/api/home/64563f1ab42629d7d4ed5c16
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDE3QGFzZC5jb20iLCJ1c2VySWQiOiI2NDQ0ZTFiYmU2ZWFjMzEzNjgyNmQ4ZTMiLCJpYXQiOjE2ODM0NTYxMjgsImV4cCI6MTY4MzQ1OTcyOH0.Lke8LCypAwJ7atnlNa8txltnkBTLTWmtWV66UqrpQq8