GET http://localhost:3000/api/home/all
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDlAYXNkLmNvbSIsInVzZXJJZCI6IjY0NDRkOGYyZTZlYWMzMTM2ODI2ZDg5ZiIsImlhdCI6MTY4NDA2NDA4NywiZXhwIjoxNjg0MDY3Njg3fQ.CMPv60f3CDd-9242l3mLHD4FwQHklD3-KYyV_viTq6U

###

GET http://localhost:3000/api/home/645622c0441ea2b6f17deb4e
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDIwQGFzZC5jb20iLCJ1c2VySWQiOiI2NDQ5NDdmN2MyYjJjNTU0N2NjZjM5NGIiLCJpYXQiOjE2ODM5MDgzMzAsImV4cCI6MTY4MzkxMTkzMH0.e40k_JHHQ-kxa6ewaL9qzv99ZwNGllpuAsCu3os423s

###

GET http://localhost:3000/api/home/64563f1ab42629d7d4ed5c16
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDIwQGFzZC5jb20iLCJ1c2VySWQiOiI2NDQ5NDdmN2MyYjJjNTU0N2NjZjM5NGIiLCJpYXQiOjE2ODM5MDgzMzAsImV4cCI6MTY4MzkxMTkzMH0.e40k_JHHQ-kxa6ewaL9qzv99ZwNGllpuAsCu3os423s