GET http://localhost:3000/api/home/all
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDE5QGFzZC5jb20iLCJ1c2VySWQiOiI2NDQ1MGZiMjJiNTdjZTU3YzlhOGFlYjEiLCJpYXQiOjE2ODM0NTQ2MjIsImV4cCI6MTY4MzQ1ODIyMn0.ZYTYkU04mCyZ3UPPmP0x4KhjltxyQvqRSB68jIcx3bM