GET http://localhost:3000/api/device/swapStatus/64679a8ed1ccebf1d778fda2
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDEwQGFzZC5jb20iLCJ1c2VySWQiOiI2NDQ0ZDk0OGU2ZWFjMzEzNjgyNmQ4YTUiLCJpYXQiOjE2ODQ1NjYyMzYsImV4cCI6MTY4NDU2OTgzNn0.4OSH9Pr_5mITJEPI-HYPAdR6CslLX3hXGAiF2Zm0uko
